### ISSUE TITLE
questions about new_unlab.json and the unlabel data missing

### ISSUE THREAD

**Issue by tangyuhao2016** [csalt-research/perturb-predict-paraphrase#2]
Thank you very much for opening such great work.

When I run the trainstudent.py, I found that the unlabel data was missing. I want to know how new_unlab.json is obtained and how can I get the data in new_unlab.json. I has download the cocobu_att, cocobu_fc, cocotalk_att, cocotalk_fc.

No such file or directory: '../172679.npz'  This is the error and I can not find the data of new_unlab.json in cocobu and cocotalk.

**Comment by ArjitJ** [comment]
You will need to download the unlabeled COCO images from https://cocodataset.org/, and follow the instructions on https://github.com/peteanderson80/bottom-up-attention to extract bottom-up attention features for the unlabeled dataset. 

You could also use the ConceptualCaptions dataset for your unlabeled images. The pre-extracted bottom-up features are readily available at https://github.com/ruotianluo/GoogleConceptualCaptioning#download-neccesary-files-to-data.
